AllCops:
  Exclude:
    - 'db/schema.rb'
    - bin/*

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'config/initializers/rack_mini_profiler.rb'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/HandleExceptions:
  Enabled: false

Metrics/AbcSize:
  Max: 15
  Exclude:
    - 'config/initializers/rack_mini_profiler.rb'

Metrics/LineLength:
  Max: 160

Style/AndOr:
  EnforcedStyle: conditionals

Style/CommentedKeyword:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
