AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'config/initializers/rack_mini_profiler.rb'

Lint/HandleExceptions:
  Enabled: false

Metrics/AbcSize:
  Max: 15
  Exclude:
    - 'config/initializers/rack_mini_profiler.rb'

Metrics/LineLength:
  Max: 160

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  MaxLineLength: 80

Style/NumericLiterals:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space