language: ruby
cache: bundler
services:
  - postgresql
rvm:
  - 2.6.2
bundler_args: --without servers tools
before_install:
  - gem update --system
  - gem --version
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
