# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfb142e1726fca2b1d1cc05520207fd3812601bfdc4e3d3fa6d41ddad40ff35a5f99bd96fe427a9fa0e2084657fca26cf29501b73a8846d6b8e99194d2e14716

test:
  secret_key_base: 3b2dca6c26e479e232b750f63ac7ca39860ad1009ed214a58211ed7ad925873e97c2cf7fb7dda0329a01ba3785d90c92a7c90ee6ed3d9f5a6f6bf2600c35722c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
